### ISSUE TITLE
Support Email notifications

### ISSUE THREAD

**Issue by lyz-code** [lyz-code/mkdocs-newsletter#16]
## Description

We support RSS notifications, but it can be interesting to also post the changes to a mailing list, for the people that don't use the RSS technology.

## Possible Solution

In the `on_config` event store the `Newsletter` objects created for the `weekly` type, and add a step in the `on_post_build` to send the email with the html of that newsletter.

## Additional context

I'm not sure if people would use it, so before implementing, it I'd like to see some comments on this issue or some thumbs up.

**Comment by lyz-code** [comment]
Closed till someone shows any interest in this feature

**Comment by meysam81** [comment]
+1 for this :rose: :pray:

**Comment by levoxtrip** [comment]
I would also love to be able to send a newsletter once a week with a list of all new entries!
